source 'http://rubygems.org'

gem 'bundler'
gem 'cucumber', '~> 5.2'
gem 'cuke_modeler'
gem 'httparty'
gem 'faker'
gem 'json'
gem 'nokogiri'
gem 'os'
gem 'parallel_tests'
gem 'rspec'
gem 'mime-types'
gem 'net-ssh'
gem 'write_xlsx'
gem 'pry'
gem 'json-schema'
gem 'jsonpath'
